name: Publish Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to publish (e.g., 1.0.6)'
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and create tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npm version ${{ github.event.inputs.version }} -m "chore: release v${{ github.event.inputs.version }}"
          git push --follow-tags

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Show .npmrc file
        run: cat ~/.npmrc

      - run: npm install
      
      - name: Publish to npm
        id: publish
        run: npm publish --access public

      - name: Delete tag on failure
        if: failure()
        run: |
          git push --delete origin v${{ github.event.inputs.version }}