name: Publish to npm and GPR

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    # Permissions are required for trusted publishing
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      # THIS IS THE FIX: The 'Unscope package name' step has been removed.
      # The workflow will now use the correct scoped name from package.json.

      - name: Publish to npm
        # The --provenance flag enables trusted publishing.
        # Your package.json already has "access": "public", so --access is not needed here.
        run: npm publish --provenance
        # No token is needed because trusted publishing uses OIDC.

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for GPR
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          # This token is automatically provided by GitHub for publishing to GPR.
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
